version: "3.8"

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=sass
      - MONGO_INITDB_ROOT_PASSWORD=realpasssass
      - MONGO_INITDB_DATABASE=admin
    volumes:
      - mongo-data:/data/db

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=062013
      - POSTGRES_DB=agricom
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  mongo-data:
  postgres-data:
